### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by jefke-glider** [uoregon-libraries/rais-image-server#45]
i am trying to build the rais-server, but i got an error:
jpe@srv1:~/rais-image-server$ make
go run src/transform/generator.go
go fmt src/transform/rotation.go
src/transform/rotation.go
go generate rais/src/version
go build -ldflags="-s -w" -buildmode=plugin -o bin/plugins/json-tracer.so rais/src/plugins/json-tracer
build rais/src/plugins/json-tracer: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
make: *** [Makefile:74: bin/plugins/json-tracer.so] Error 1

**Comment by jefke-glider** [comment]
ok, i have go version 1.13.8, maybe that;s the reason. gone have to compile it manually....

**Comment by jechols** [comment]
I can reproduce this with Go 1.13. RAIS definitely needs a newer go version. Grabbing the latest Go shouldn't require much manual work, though - you basically download the latest binary package available for your system, extract it, and run it. (See the [official download page](https://go.dev/dl/))

**Comment by jechols** [comment]
If you're using Linux, you can probably follow along with the info on the [Installation page of the RAIS wiki](https://github.com/uoregon-libraries/rais-image-server/wiki/Installation#prerequisites). Let me know if that doesn't work, though - I just updated it to reflect the latest Go version since Go is almost 100% backward-compatible, but not always forward-compatible.

**Comment by jefke-glider** [comment]
worked like a charm now. I am using rais-server in combination with Omeka-S! Thanks for the project.

**Comment by jechols** [comment]
Glad to hear it!
